spring:
  datasource:
    url: jdbc:mysql://localhost/gestao_negocios
    username: root
    password: root

    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 100
      validation-query: SELECT 1
      validation-query-timeout: 1000
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show-sql: false